import java.util.Scanner;
public class Main {
public static void main(String[] args){
  Scanner scan=new Scanner(System.in);
  music music1=new music();
  System.out.println("Enter the name of the music1");
  String name=scan.nextLine();
  music1.setName(name);
  System.out.println("Enter the artist of the music1");
  String artist=scan.nextLine();
  music1.setArtist(artist);
  System.out.println("Enter the release date of the music1");
  String rel_date=scan.nextLine();
  music1.setDate(rel_date);
  System.out.println("Enter the availability of the music1 on Youtube");
  String available=scan.nextLine();
  music1.setAvailable(available);
  music music2=new music();
  System.out.println("Enter the name of the music2");
  name=scan.nextLine();
  music2.setName(name);
  System.out.println("Enter the artist of the music2");
  artist=scan.nextLine();
  music2.setArtist(artist);
  System.out.println("Enter the release date of the music2");
  rel_date=scan.nextLine();
  music2.setDate(rel_date);
  System.out.println("Enter the availability of the music2 on Youtube");
  available=scan.nextLine();
  music2.setAvailable(available);
  music music3=new music();
  System.out.println("Enter the name of the music3");
  name=scan.nextLine();
  music3.setName(name);
  System.out.println("Enter the artist of the music3");
  artist=scan.nextLine();
  music3.setArtist(artist);
  System.out.println("Enter the release date of the music3");
  rel_date=scan.nextLine();
  music3.setDate(rel_date);
  System.out.println("Enter the availability of the music3 on Youtube");
  available=scan.nextLine();
  music3.setAvailable(available);
  music music4=new music();
  System.out.println("Enter the name of the music4");
  name=scan.nextLine();
  music4.setName(name);
  System.out.println("Enter the artist of the music4");
  artist=scan.nextLine();
  music4.setArtist(artist);
  System.out.println("Enter the release date of the music4");
  rel_date=scan.nextLine();
  music4.setDate(rel_date);
  System.out.println("Enter the availability of the music4 on Youtube");
  available=scan.nextLine();
  music4.setAvailable(available);
  music music5=new music();
  System.out.println("Enter the name of the music5");
  name=scan.nextLine();
  music5.setName(name);
  System.out.println("Enter the artist of the music5");
  artist=scan.nextLine();
  music5.setArtist(artist);
  System.out.println("Enter the release date of the music5");
  rel_date=scan.nextLine();
  music5.setDate(rel_date);
  System.out.println("Enter the availability of the music5 on Youtube");
  available=scan.nextLine();
  music5.setAvailable(available);
  System.out.println("The music1 is "+music1.getName()+" by "+music1.getArtist()+" released on "+music1.getRel_date()+" and is "+music1.musicAction()+"for avability on Youtube");
  System.out.println("The music2 is "+music2.getName()+" by "+music2.getArtist()+" released on "+music2.getRel_date()+" and is "+music2.musicAction()+"for avability on Youtube");
  System.out.println("The music3 is "+music3.getName()+" by "+music3.getArtist()+" released on "+music3.getRel_date()+" and is "+music3.musicAction()+"for avability on Youtube");
  System.out.println("The music4 is "+music4.getName()+" by "+music4.getArtist()+" released on "+music4.getRel_date()+" and is "+music4.musicAction()+"for avability on Youtube");
  System.out.println("The music5 is "+music5.getName()+" by "+music5.getArtist()+" released on "+music5.getRel_date()+" and is "+music5.musicAction()+"for avability on Youtube");
  }
}
